### ISSUE TITLE
Creat Word Count Metrics Page

### ISSUE THREAD

**Issue by singularityhacker** [singularityhacker/agile-automata#3]
**Current State**

The word-count GitHub action has already been created and it works fantastic. Seen [here](https://github.com/singularityhacker/Content). It lists each markdown file in a repository and every edit is listed with the date, the diff, and current word count.

**Problem Statement**

It's hard to grasp how writing goals are being met on a daily basis by looking at a JSON file.

**Proposed Solution**

Create a special page that visually represents the word count data. Github's Jekyll pages would seem to be a great way to do this. 

**The Task**

Take an existing Github Jekyll pages repo, add the word count workflow to it, then create a special page in that repo that renders the JSON data in markup similar to [this](https://stackoverflow.com/questions/23983364/how-to-load-data-from-json-in-jekyll) so that a person can more easily see their writing history in order to confirm daily word count writing goals. 

**Resources**

1.  This is a Github pages site I already have going. It can be used if desired: 
    1.  https://github.com/singularityhacker/agile-automata
    2.  https://agileautomata.com/
2.  There appears to be an existing mechanism to use local JSON data in Jekyll:
    1.  https://jekyllrb.com/docs/datafiles/

**Comment by singularityhacker** [comment]
@mhatvan, would you be interested in taking this on? If so, I can apply a bounty consistent with the effort you estimate or you can just track your time and I'll pay after it's finished. Whichever you would prefer. Happy holidays to you, friend. Hope you are doing well.

**Comment by mcmxcdev** [comment]
Hey Justice, sure thing, always up for a challenge! ;)
I will go over the task and think about an estimate in the next few days.
Happy holidays to you and your family as well.

**Comment by singularityhacker** [comment]
Fantastic! Glad to hear it.

**Comment by mcmxcdev** [comment]
I took a look at this issue again, and I am unsure about how you imagine the metrics page should look like. 
Can you provide a simple mockup? Or specify further?
Do you want the page to have graphs on it or just the number of the diff in green/red based on the daily change?

I would be tracking the time because it is hard to estimate the scope based on the provided information.

**Comment by singularityhacker** [comment]
Of course. I'm thinking we can do mini sprints. You get a little done then we check it out and then refocus. Here's the big picture I'd like to pursue: https://i.imgur.com/HI2ouDh.png

Does it make sense to you? We can start really small tho. Just getting it displaying in markup would be a good start.

**Comment by singularityhacker** [comment]
This whole idea is based around a "don't break the chain" method of writing but git-centric and free. It's a part of a series I'm working on called ContentOps. If that background gives you a little insight.

**Comment by singularityhacker** [comment]
I could prepay for multi-hour (4 hr) buckets and then you update on progress when that time is exhausted then we repeat the process cyclicly and see where this goes. I can pay you directly in crypto as well if you'd like.

**Comment by singularityhacker** [comment]
Created: https://github.com/singularityhacker/Content_Ops
